# Generated by Django 4.1 on 2022-08-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-date_added",)},
        ),
    ]
